accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import CreateUser, LoginUser, LogoutUser, UpdateUser, DeleteUser,\
    CreateAdminUser, UpdateAdminUser, DeleteAdminUser, LoginAdminUser, LogoutAdminUser, \
    AdminProfileList, UserList, View

app_name='accounts'

urlpatterns = [
    path('view', View.as_view(), name='view'),
    #create admin/user
    path('signup', CreateUser.as_view(), name='signup'),
    path('admin_signup', CreateAdminUser.as_view(), name='admin'),
    #login admin/user
    path('login', LoginUser.as_view(), name='login'),
    path('admin_login', LoginAdminUser.as_view(), name='admin_login'),
    #logout admin/user
    path('logout', LogoutUser, name='logout'),
    path('admin_logout', LogoutAdminUser, name='admin_logout'),
    #list admin/user
    path('user', UserList.as_view(), name='user'),
    path('admin_user', AdminProfileList.as_view(), name='admin_user'),
    #update admin/user
    path('update/<pk>', UpdateUser.as_view(), name='update'),
    path('admin_update/<pk>', UpdateAdminUser.as_view(), name='admin_update'),
    #delete admin/user
    path('delete/<pk>', DeleteUser.as_view(), name='delete'),
    path('admin_delete/<pk>', DeleteAdminUser.as_view(), name='admin_delete'),
    #password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uid64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

report/urls.py
from django.urls import path
from .views import ReportFormView, FileUploadFormView, ListReportFormView, ListFileUploadFormView, \
    UpdateFileUploadFormView, UpdateReportFormView, DeleteFileUploadFormView, DeleteReportFormView, \
    DashboardView, ChoosePage, send_pdf, download_pdf

app_name = 'report'

urlpatterns = [
    path('', DashboardView.as_view(), name='home'),
    path('choose', ChoosePage.as_view(), name='choose'),
    #Pdf
    path('pdf_view', send_pdf, name='pdf_view'),
    path('pdf_download', download_pdf, name='pdf_download'),
    #ReportForm
    path('report_form_view', ReportFormView.as_view(), name='report'),
    path('list_report_form_view', ListReportFormView.as_view(), name='list_report'),
    path('update_report_form_view/<pk>', UpdateReportFormView.as_view(), name='update_report'),
    path('delete_report_form_view/<pk>', DeleteReportFormView.as_view(), name='delete_report'),
    #FileUpload
    path('fileupload_form_view', FileUploadFormView.as_view(), name='fileupload'),
    path('list_fileupload_form_view', ListFileUploadFormView.as_view(), name='list_fileupload'),
    path('update_fileupload_form_view/<pk>', UpdateFileUploadFormView.as_view(), name='update_fileupload'),
    path('delete_fileupload_form_view/<pk>', DeleteFileUploadFormView.as_view(), name='delete_fileupload'),
]

web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('report.urls')),
    path('', include('accounts.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User


class UserCreateForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserLoginForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        
class UserUpdatForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')
        
class AdminCreateForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password','is_staff', 'is_superuser')

class AdminLoginForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        
class AdminUpdatForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'is_staff', 'is_superuser')

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin


from .forms import UserCreateForm, AdminCreateForm, UserLoginForm, AdminLoginForm, UserUpdatForm, AdminUpdatForm
# Create your views here.

def is_admin(user):
    return user.is_authenticated and user.is_staff
class View(TemplateView):
    template_name = 'views.html'

class CreateUser(CreateView):
    template_name = 'create.html'
    queryset = User.objects.all()
    form_class = UserCreateForm
    
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')
            
            user = User.objects.create_user(username, email, password)
            user.save()
            return redirect('/login')
        else:
            return render("Inavlid Signup")
        
class LoginUser(CreateView):
    template_name = 'login.html'
    queryset = User.objects.all()
    form_class = UserLoginForm
    
    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/choose')
        else:
            return HttpResponse('details : User Not Found')
    
    
def LogoutUser(request):
    logout(request)
    return redirect('/login')

class UserList(LoginRequiredMixin, ListView):
    template_name = 'users.html'
    queryset = User.objects.all()
    context_object_name = 'users'
    login_url ='/login'

    # Filter the queryset to include only normal users
    def get_queryset(self):
        return User.objects.filter(is_staff=False)

class UpdateUser(LoginRequiredMixin, UpdateView):
    template_name = 'update.html'
    queryset = User.objects.all()
    form_class = UserUpdatForm
    success_url = '/user'
    login_url ='/login'
    
class DeleteUser( LoginRequiredMixin, DeleteView):
    template_name = 'delete.html'
    queryset = User.objects.all()
    context_object_name = 'user_delete'
    success_url = '/user'
    login_url ='/login'
        
class CreateAdminUser(CreateView):
    template_name = 'admin_signup.html'
    queryset = User.objects.all()
    form_class = AdminCreateForm
    
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')
            
            user = User.objects.create_superuser(username, email, password)
            user.save()
            return redirect('/admin_login')
        else:
            return render("Inavlid Admin Signup")

class LoginAdminUser(CreateView):
    template_name = 'admin_login.html'
    queryset = User.objects.all()
    form_class = AdminLoginForm
    
    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_staff:
            login(request, user)
            return redirect('/view')
        else:
            return HttpResponse('details : Admin User Not Found')
    
def LogoutAdminUser(request):
    logout(request)
    return redirect('/admin_login')
    
class AdminProfileList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    template_name = 'admin_users.html'
    queryset = User.objects.all()
    context_object_name = 'admin'
    login_url ='/admin_login'

    def test_func(self):
        return is_admin(self.request.user)
    
    # Filter the queryset to include only admin users
    def get_queryset(self):
        return User.objects.filter(is_staff=True)
    
class UpdateAdminUser(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'admin_update.html'
    queryset = User.objects.all()
    form_class = AdminUpdatForm
    success_url = '/admin_user'
    login_url ='/admin_login'

    def test_func(self):
        return is_admin(self.request.user)

class DeleteAdminUser(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'admin_delete.html'
    queryset = User.objects.all()
    context_object_name = 'admin_delete'
    success_url = '/admin_user'
    login_url ='/admin_login'

    def test_func(self):
        return is_admin(self.request.user)
    

accounts/templates/admin_delete.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    {% if request.user.is_authenticated and request.user.is_staff %}
    <p class="font-sans font-bold text-black text-center">
    Are you sure you want to delete {{ admin_delete.username }}
    </p>
    <form method="post">
        {% csrf_token %}
        <button 
        type="submit"
        class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 px-14 text-center font-sans font-bold border">
        Delete
        </button>
    </form>
    {% else %}
        <!-- Content for non-admin users or users not logged in -->
        <p>You don't have permission to access this content.</p>
        <!-- Add more content for non-admin users here -->
    {% endif %}
</div>
{% endblock %} 

accounts/templates/admin_login.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    <h1 class="text-3xl text-center font-sans font-extrabold">ADMIN LOG IN</h1>
    <br/>
    <br/>
    <form method="post" class="md:mx-20 mx-8">
        {% csrf_token %}
        <label 
        class="font-sans font-bold text-black text-left">Username:
            <input
            class="md:rounded rounded-2xl px-10" 
            id="username" 
            placeholder="Username"
            type="text"  
            name="username">
        </label>
        <br/>
        <br/>
        <label
        class="font-sans font-bold text-black text-left">Password:
            <input 
            class="md:rounded rounded-2xl px-10"
            id="password" 
            placeholder="Password"
            type="password"  
            name="password">
        </label>
        <br/>
        <br/>
        <button 
        type="submit"
        class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 px-14 text-center font-sans font-bold border">
        Login
        </button>
    </form>
</div>
{% endblock %} 

accounts/templates/admin_signup.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    <h1 class="text-3xl text-center font-sans font-extrabold">ADMIN SIGN UP</h1>
    <br/>
    <br/>
    <form method="post" class="md:mx-20 mx-8">
        {% csrf_token %}
        <label
        class="font-sans font-bold text-black text-left">Username:
            <input
            class="md:rounded rounded-2xl px-10" 
            id="username" 
            placeholder="Username"
            type="text"  
            name="username">
        </label>
        <br/>
        <br/>
        <label
        class="font-sans font-bold text-black text-left">Email:
            <input 
            class="md:rounded rounded-2xl px-10" 
            id="email"
            placeholder="Email"
            type="email" 
            name="email">
        </label>
        <br/>
        <br/>
        <label
        class="font-sans font-bold text-black text-left">Password:
            <input
            class="md:rounded rounded-2xl px-10"
            id="password" 
            placeholder="Password"
            type="password"  
            name="password">
        </label>
        <br/>
        <br/>
        <label
        class="font-sans font-bold text-black text-left">Is Staff:
            <input
            class="rounded"
            id="is_staff" 
            placeholder="Is Staff"
            type="checkbox"  
            name="is_staff">
        </label>
        <br/>
        <br/>
        <label
        class="font-sans font-bold text-black text-left">Is SuperUser:
            <input
            class="rounded"
            id="is_superuser" 
            placeholder="Is SuperUser"
            type="checkbox"  
            name="is_superuser">
        </label>
        <br/>
        <br/>
        <button 
        type="submit"
        class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 px-14 text-center font-sans font-bold border">
        Sign up
        </button>
    </form>
</div>
{% endblock %} 

accounts/templates/admin_update.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    {% if request.user.is_authenticated and request.user.is_staff %}
    <h1 class="text-3xl text-center font-sans font-extrabold">ADMIN UPDATE</h1>
    <br/>
    <br/>
    <form method="post" class="md:mx-20 mx-8">
        {% csrf_token %}
        <label
        class="font-sans font-bold text-black text-left">Username:
            <input
            class="md:rounded rounded-2xl px-10" 
            id="username" 
            placeholder="Username"
            type="text"  
            name="username">
        </label>
        <br/>
        <br/>
        <label
        class="font-sans font-bold text-black text-left">Email:
            <input 
            class="md:rounded rounded-2xl px-10" 
            id="email"
            placeholder="Email"
            type="email" 
            name="email">
        </label>
        <br/>
        <br/>
        <!--<label
        class="font-sans font-bold text-black text-left">Password:
            <input
            class="md:rounded rounded-2xl px-10"
            id="password" 
            placeholder="Password"
            type="password"  
            name="password">
        </label>
        <br/>
        <br/> -->
        <label
        class="font-sans font-bold text-black text-left">Is Staff:
            <input
            class="rounded"
            id="is_staff" 
            placeholder="Is Staff"
            type="checkbox"  
            name="is_staff">
        </label>
        <br/>
        <br/>
        <label
        class="font-sans font-bold text-black text-left">Is SuperUser:
            <input
            class="rounded"
            id="is_superuser" 
            placeholder="Is SuperUser"
            type="checkbox"  
            name="is_superuser">
        </label>
        <br/>
        <br/>
        <button 
        type="submit"
        class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 px-14 text-center font-sans font-bold border">
        Sign up
        </button>
    </form>
    {% else %}
        <!-- Content for non-admin users or users not logged in -->
        <p>You don't have permission to access this content.</p>
        <!-- Add more content for non-admin users here -->
    {% endif %}
</div>
{% endblock %} 

accounts/templates/admin_users.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    <ul>
        {% if request.user.is_authenticated and request.user.is_staff %}
        <div>
            {% for user in admin %}
            <li 
            class="font-sans font-bold text-black text-left">
            User Name : {{ user.username}}
            </li>
            <li
            class="font-sans font-bold text-black text-left">
            Email : {{ user.email}}
            </li>
            <li 
            class="font-sans font-bold text-black text-left">
            Password : *******************
            </li>
<<<<<<< HEAD
            <br/>
            <div class="flex">
                <button>
                    <a 
                    href="{% url 'accounts:admin_update' pk=user.id %}" 
                    class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 ml-1 py-3 md:px-14 px-5 text-center font-sans font-bold border">
                    Update
                    </a>
                </button>
                <button>
                    <a 
                    href="{% url 'accounts:admin_delete' pk=user.id %}" 
                    class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 mx-5 py-3 md:px-14 px-5 text-center font-sans font-bold border">
                    Delete
                    </a>
                </button>
                <button>
                    <a 
                    href="{% url 'accounts:admin_logout' %}" 
                    class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 md:px-14 px-3 text-center font-sans font-bold border">
                    Admin logout
                    </a>
                </button>
            </div>
            <br/>
=======
>>>>>>> 9d404d1debb65a2c3c7c519e724e5374ca0d9874
            {% endfor %}
        </div>
        <br/>
        {% else %}
            <!-- Content for non-admin users or users not logged in -->
            <p>You don't have permission to access this content.</p>
            <!-- Add more content for non-admin users here -->
        {% endif %}
    </ul>
</div>
{% endblock %} 

accounts/templates/create.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    <h1 class="text-3xl text-center font-sans font-extrabold">SIGN UP</h1>
    <br/>
    <br/>
    <form method="post" class="md:mx-20 mx-8">
        {% csrf_token %}
        <label
        class="font-sans font-bold text-black text-left">Username:
            <input
            class="md:rounded rounded-2xl px-10" 
            id="username" 
            placeholder="Username"
            type="text"  
            name="username">
        </label>
        <br/>
        <br/>
        <label
        class="font-sans font-bold text-black text-left">Email:
            <input 
            class="md:rounded rounded-2xl px-10" 
            id="email"
            placeholder="Email"
            type="email" 
            name="email">
        </label>
        <br/>
        <br/>
        <label
        class="font-sans font-bold text-black text-left">Password:
            <input
            class="md:rounded rounded-2xl px-10"
            id="password" 
            placeholder="Password"
            type="password"  
            name="password">
        </label>
        <br/>
        <br/>
        <button 
        type="submit"
        class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 px-14 text-center font-sans font-bold border">
        Sign up
        </button>
    </form>
</div>
{% endblock %} 

accounts/templates/delete.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    <p 
    class="font-sans font-bold text-black text-center">
    Are you sure you want to delete {{ user_delete.username }}
    </p>
    <form method="post">
        {% csrf_token %}
        <button 
        type="submit"
        class="bg-blue-900 text-white text-sm rounded-lg mt-3 py-3 px-14 text-center font-sans font-bold border">
        Delete
        </button>
    </form>
</div>
{% endblock %} 

accounts/templates/login.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 md:mx-80 mx-12 md:p-5 bg-white rounded-lg">
    <br/>
    <h1 class="text-3xl text-center font-sans font-extrabold">LOG IN</h1>
    <form method="post" class="md:mx-16">
        {% csrf_token %}
        <div class="my-5 md:mx-24 mx-16 py-5">
            <label 
            class="font-sans font-bold text-black text-left" for="username">Username :
                <input 
                class="md:rounded rounded-2xl px-10" 
                id="username" 
                placeholder="Username"
                type="text"  
                name="username">
            </label>
            <br/>
            <br/>
            <label 
            class="font-sans font-bold text-black text-left" for="password">Password :
                <input 
                class="md:rounded rounded-2xl px-10"
                id="password" 
                placeholder="Password"
                type="password"  
                name="password">
            </label>
            <br/>
            <br/>
            <button 
            class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 px-14 text-center font-sans font-bold border" 
            type="submit"
            >Sign in
            </button>
        </div>
    </form>
</div>
{% endblock %} 

accounts/templates/password_reset.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 mx-80 p-5 bg-white rounded-lg">
    <h1>Password Reset</h1>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button 
        type="submit"
        class="bg-blue-900 text-white text-sm rounded-lg mt-3 py-3 px-14 text-center font-sans font-bold border">
        </button>
    </form>
</div>
{% endblock %} 

accounts/templates/password_reset_complete.html
{% extends "base.html" %}
{% load static tailwind_tags %}

{% block contents %}
<div class="my-32 mx-80 p-5 bg-white rounded-lg">
    <h3>Password Reset Complete</h3>
    <button>
        <a 
        href="{% url 'accounts:login' %}"
        class="bg-blue-900 text-white text-sm rounded-lg mt-3 py-3 px-14 text-center font-sans font-bold border">
        Login
        </a>
    </button>
</div>
{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 mx-80 p-5 bg-white rounded-lg">
    <h1>Enter New Password</h1>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button 
        type="submit"
        class="bg-blue-900 text-white text-sm rounded-lg mt-3 py-3 px-14 text-center font-sans font-bold border">
        submit
        </button>
    </form>
</div>
{% endblock %} 

accounts/templates/password_reset_done.html
<h3>Password Reset Sent</h3>

accounts/templates/users.html
{% extends 'base.html' %}
{% load static tailwind_tags %}


{% block contents %} 
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    <ul>
        {% if request.user.is_authenticated %}
        <div>
            {% for user in users %}
            <li
            class="font-sans font-bold text-black text-left">
            User Name : {{ user.username}}
            </li>
            <li
            class="font-sans font-bold text-black text-left">
            Email : {{ user.email}}
            </li>
            <li 
            class="font-sans font-bold text-black text-left">
            Passowrd : *******************
            </li>
            <br/>
            <div class="flex">
                <button>
                    <a 
                    href="{% url 'accounts:update' pk=user.id %}" 
                    class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 mr-5 py-3 md:px-14 px-5 text-center font-sans font-bold border">
                    Update
                    </a>
                </button>
                <button>
                    <a 
                    href="{% url 'accounts:delete' pk=user.id %}" 
                    class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 ml-5 py-3 md:px-14 p-5 text-center font-sans font-bold border">
                    Delete
                    </a>
                </button>
            </div>
            <br/>
            {% endfor %}
        </div>
        {% endif %}
    </ul>
</div>
{% endblock %} 

accounts/templates/views.html
{% extends "base.html" %}
{% load static tailwind_tags %}

{% block contents  %}
<div class="my-32 md:mx-80 mx-12 px-5 py-14 bg-white rounded-lg"> 
    <div class="flex">  
        <button>
            <a 
            href="{% url 'accounts:admin_user' %}" 
            class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 md:ml-4 md:px-10 px-3 text-center font-sans font-bold border">
            Admin Users
            </a>
        </button>
        <button>
            <a 
            href="{% url 'accounts:user' %}" 
            class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 md:mx-14 mx-5 py-3 md:px-14 px-6 text-center font-sans font-bold border">
            Users
            </a>
        </button>
        <button>
            <a 
            href="{% url 'accounts:signup' %}" 
            class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 md:px-10 px-3 text-center font-sans font-bold border">
            Sign Up Users
            </a>
        </button>
    </div>
</div>
{% endblock  %}