accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import CreateUser, LoginUser, LogoutUser, UpdateUser, DeleteUser,\
    CreateAdminUser, UpdateAdminUser, DeleteAdminUser, LoginAdminUser, LogoutAdminUser, \
    AdminProfileList, UserList, View

app_name='accounts'

urlpatterns = [
    path('view', View.as_view(), name='view'),
    #create admin/user
    path('signup', CreateUser.as_view(), name='signup'),
    path('admin_signup', CreateAdminUser.as_view(), name='admin'),
    #login admin/user
    path('login', LoginUser.as_view(), name='login'),
    path('admin_login', LoginAdminUser.as_view(), name='admin_login'),
    #logout admin/user
    path('logout', LogoutUser, name='logout'),
    path('admin_logout', LogoutAdminUser, name='admin_logout'),
    #list admin/user
    path('user', UserList.as_view(), name='user'),
    path('admin_user', AdminProfileList.as_view(), name='admin_user'),
    #update admin/user
    path('update/<pk>', UpdateUser.as_view(), name='update'),
    path('admin_update/<pk>', UpdateAdminUser.as_view(), name='admin_update'),
    #delete admin/user
    path('delete/<pk>', DeleteUser.as_view(), name='delete'),
    path('admin_delete/<pk>', DeleteAdminUser.as_view(), name='admin_delete'),
    #password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uid64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

report/urls.py
from django.urls import path
from .views import ReportFormView, FileUploadFormView, ListReportFormView, ListFileUploadFormView, \
    UpdateFileUploadFormView, UpdateReportFormView, DeleteFileUploadFormView, DeleteReportFormView, \
    DashboardView, ChoosePage, send_pdf, download_pdf

app_name = 'report'

urlpatterns = [
    path('', DashboardView.as_view(), name='home'),
    path('choose', ChoosePage.as_view(), name='choose'),
    #Pdf
    path('pdf_view', send_pdf, name='pdf_view'),
    path('pdf_download', download_pdf, name='pdf_download'),
    #ReportForm
    path('report_form_view', ReportFormView.as_view(), name='report'),
    path('list_report_form_view', ListReportFormView.as_view(), name='list_report'),
    path('update_report_form_view/<pk>', UpdateReportFormView.as_view(), name='update_report'),
    path('delete_report_form_view/<pk>', DeleteReportFormView.as_view(), name='delete_report'),
    #FileUpload
    path('fileupload_form_view', FileUploadFormView.as_view(), name='fileupload'),
    path('list_fileupload_form_view', ListFileUploadFormView.as_view(), name='list_fileupload'),
    path('update_fileupload_form_view/<pk>', UpdateFileUploadFormView.as_view(), name='update_fileupload'),
    path('delete_fileupload_form_view/<pk>', DeleteFileUploadFormView.as_view(), name='delete_fileupload'),
]

web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('report.urls')),
    path('', include('accounts.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Weekly Report</title>
  <link rel="stylesheet" href="{% static './css/style.css' %}" />
  {% tailwind_css %}
</head>
<body class="bg-blue-900">
{% block contents  %}
{% endblock  %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static tailwind_tags %}

{% block contents  %}
<div class="my-32 md:mx-80 mx-10 p-5 bg-white rounded-lg">   
  <button><a href="{% url 'accounts:login' %}" class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 md:mx-64 mx-32 py-3 md:px-12 px-12 text-center font-sans font-bold border">Login</a></button>
</div>
{% endblock  %}

templates/html.html
<li><a href="{% url 'accounts:admin_login' %}" class="">Admin login</a></li>
<li><a href="{% url 'accounts:admin' %}" class="">Admin signup</a></li>