accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import CreateUser, LoginUser, LogoutUser, UpdateUser, DeleteUser,\
    CreateAdminUser, UpdateAdminUser, DeleteAdminUser, LoginAdminUser, LogoutAdminUser, \
    AdminProfileList, UserList, View

app_name='accounts'

urlpatterns = [
    path('view', View.as_view(), name='view'),
    #create admin/user
    path('signup', CreateUser.as_view(), name='signup'),
    path('admin_signup', CreateAdminUser.as_view(), name='admin'),
    #login admin/user
    path('login', LoginUser.as_view(), name='login'),
    path('admin_login', LoginAdminUser.as_view(), name='admin_login'),
    #logout admin/user
    path('logout', LogoutUser, name='logout'),
    path('admin_logout', LogoutAdminUser, name='admin_logout'),
    #list admin/user
    path('user', UserList.as_view(), name='user'),
    path('admin_user', AdminProfileList.as_view(), name='admin_user'),
    #update admin/user
    path('update/<pk>', UpdateUser.as_view(), name='update'),
    path('admin_update/<pk>', UpdateAdminUser.as_view(), name='admin_update'),
    #delete admin/user
    path('delete/<pk>', DeleteUser.as_view(), name='delete'),
    path('admin_delete/<pk>', DeleteAdminUser.as_view(), name='admin_delete'),
    #password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uid64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

report/urls.py
from django.urls import path
from .views import ReportFormView, FileUploadFormView, ListReportFormView, ListFileUploadFormView, \
    UpdateFileUploadFormView, UpdateReportFormView, DeleteFileUploadFormView, DeleteReportFormView, \
    DashboardView, ChoosePage, send_pdf, download_pdf

app_name = 'report'

urlpatterns = [
    path('', DashboardView.as_view(), name='home'),
    path('choose', ChoosePage.as_view(), name='choose'),
    #Pdf
    path('pdf_view', send_pdf, name='pdf_view'),
    path('pdf_download', download_pdf, name='pdf_download'),
    #ReportForm
    path('report_form_view', ReportFormView.as_view(), name='report'),
    path('list_report_form_view', ListReportFormView.as_view(), name='list_report'),
    path('update_report_form_view/<pk>', UpdateReportFormView.as_view(), name='update_report'),
    path('delete_report_form_view/<pk>', DeleteReportFormView.as_view(), name='delete_report'),
    #FileUpload
    path('fileupload_form_view', FileUploadFormView.as_view(), name='fileupload'),
    path('list_fileupload_form_view', ListFileUploadFormView.as_view(), name='list_fileupload'),
    path('update_fileupload_form_view/<pk>', UpdateFileUploadFormView.as_view(), name='update_fileupload'),
    path('delete_fileupload_form_view/<pk>', DeleteFileUploadFormView.as_view(), name='delete_fileupload'),
]

web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('report.urls')),
    path('', include('accounts.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.
class Form(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    supervisor = models.CharField(max_length=20, default='The Chairman')
    monday = models.CharField(max_length=100)
    tuesday = models.CharField(max_length=100)
    wednessday = models.CharField(max_length=100)
    thursday = models.CharField(max_length=100)
    friday = models.CharField(max_length=100)
    monday1 = models.CharField(max_length=100)
    tuesday1 = models.CharField(max_length=100)
    wednessday1 = models.CharField(max_length=100)
    thursday1 = models.CharField(max_length=100)
    friday1 = models.CharField(max_length=100)
    projects = models.IntegerField()
    study_materials = models.IntegerField()
    rating = models.IntegerField()
    challenges = models.CharField(max_length=100)
    monday2 = models.TimeField()
    tuesday2 = models.TimeField()
    wednessday2 = models.TimeField()
    thursday2 = models.TimeField()
    friday2 = models.TimeField()
    whatsapp = models.IntegerField()
    facebook = models.IntegerField()
    twitter = models.IntegerField()
    instagram = models.IntegerField()
    monday3 = models.CharField(max_length=100)
    tuesday3 = models.CharField(max_length=100)
    wednessday3 = models.CharField(max_length=100)
    thursday3 = models.CharField(max_length=100)
    friday3 = models.CharField(max_length=100) 
    sugestions = models.CharField(max_length=100)   
    total_weeks = models.CharField(max_length=20)
    monday4 = models.IntegerField()
    tuesday4 = models.IntegerField()
    wednessday4 = models.IntegerField()
    thursday4 = models.IntegerField()
    friday4 = models.IntegerField()
    
class FileUpload(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    files = models.FileField(upload_to='files/')
    
    def extension(self):
        _, file_extension = os.path.splitext(self.files.name)
        return file_extension

report/forms.py
from django.forms import ModelForm
from .models import Form, FileUpload

class ReportForm(ModelForm):
    
    class Meta:
        model = Form
        fields = ('__all__')
        
class FileUploadForm(ModelForm):
    
    class Meta:
        model = FileUpload
        fields = ('__all__')
        

report/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import EmailMessage
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView,UpdateView, DeleteView, TemplateView
from django.conf import settings
import os

from .models import Form, FileUpload
from .forms import ReportForm, FileUploadForm
from .utils import send_file_upload_email, render_to_pdf

class DashboardView(TemplateView):
    template_name = 'home.html'

class FileUploadFormView(LoginRequiredMixin, CreateView):
    template_name = 'file_upload.html'
    queryset = FileUpload.objects.all()
    form_class = FileUploadForm
    login_url ='/login'
        
    def form_valid(self, form):
        file_upload = form.save(commit=False)
        file_upload.user = self.request.user
        file_upload.save()
        send_file_upload_email(file_upload)
        return super().form_valid(form)


class ReportFormView(LoginRequiredMixin, CreateView):
    template_name = 'report_form.html'
    queryset = Form.objects.all()
    form_class = ReportForm
    success_message = 'report submitted successfully'
    login_url ='/login'
        
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = ReportForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/list_report_form_view')
        else:
            form = ReportForm()
            
        return render(request, self.template_name, {'form': form})
    
    
def send_pdf(request):
    data = Form.objects.all()
    context = {'report': data}
    
    pdf = render_to_pdf('list_report.html', context)
    
    temp_pdf_path = 'temp_pdf.pdf'
    with open(temp_pdf_path, 'wb') as temp_pdf:
        temp_pdf.write(pdf.content)
        
    subject = 'Weekly Report'
    message = 'Attached is the PDF file.'
    from_email = settings.EMAIL_HOST_USER
    recipient_list = ['gabrielwilliams@torbitalimited.com']
    
    email = EmailMessage(subject, message, from_email, recipient_list)
    email.attach_file(temp_pdf_path)
    email.send()
    
    os.remove(temp_pdf_path)
        
    return HttpResponse('PDF sent to email successfully')
    
    
def download_pdf(request):
    data = Form.objects.all()
    context = {'report': data}
    pdf = render_to_pdf('list_report.html', context)
    return pdf

class ChoosePage(LoginRequiredMixin, TemplateView):
    template_name = 'choose.html'
    login_url ='/login'
            
    
class ListFileUploadFormView(LoginRequiredMixin, ListView):
    template_name = 'list_fileupload.html'
    context_object_name = 'fileupload'
    login_url = '/login'

    def get_queryset(self):
        return FileUpload.objects.filter(user=self.request.user)


class ListReportFormView(LoginRequiredMixin, ListView):
    template_name = 'list_report.html'
    context_object_name = 'report'
    login_url ='/login'
    
    def get_queryset(self):
        return Form.objects.filter(user=self.request.user)
    
class UpdateFileUploadFormView(LoginRequiredMixin, UpdateView):
    template_name = 'update_fileupload.html'
    queryset = FileUpload.objects.all()
    form_class = FileUploadForm
    login_url ='/login'
    
    def form_valid(self, form):
        file_upload = form.save(commit=False)
        file_upload.user = self.request.user
        file_upload.save()
        send_file_upload_email(file_upload)
        return super().form_valid(form)
    
class UpdateReportFormView(LoginRequiredMixin, UpdateView):
    template_name = 'update_report.html'
    queryset = Form.objects.all()
    form_class = ReportForm
    success_message = 'report updated successfully'
    login_url ='/login'
    
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = ReportForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/list_report_form_view')
        else:
            form = ReportForm()
            
        return render(request, self.template_name, {'form': form})
    
class DeleteFileUploadFormView(LoginRequiredMixin, DeleteView):
    template_name = 'delete_fileupload.html'
    queryset = FileUpload.objects.all()
    context_object_name = 'fileupload'
    success_url = '/fileupload_form_view'
    login_url ='/login'

    
class DeleteReportFormView(LoginRequiredMixin, DeleteView):
    template_name = 'delete_report.html'
    queryset = Form.objects.all()
    context_object_name = 'delete'
    success_url = '/report_form_view'
    login_url ='/login'
    

report/templates/choose.html
{% extends "base.html" %}
{% load static tailwind_tags %}

{% block contents  %}
<div class="flex my-32 md:mx-80 mx-10 px-5 py-10 bg-white rounded-lg"> 
    <div class="md:mx-20 mx-10">  
        <button>
            <a 
            href="{% url 'report:report' %}" 
            class="bg-blue-900 text-white text-sm rounded-2xl mt-3 py-3 md:px-12 px-5 text-center font-sans font-bold border">
            Fill Report
            </a>
        </button>
    </div>
    <div class="md:mx-14 mx-5">
        <button>
            <a 
            href="{% url 'report:fileupload' %}" 
            class="bg-blue-900 text-white text-sm rounded-2xl mt-3 py-3 md:px-12 px-5 text-center font-sans font-bold border">
            File Upload
            </a>
        </button>
    <div>
</div>
{% endblock  %}

report/templates/delete_fileupload.html
{% extends "base.html" %}
{% load static tailwind_tags %}

{% block contents %}
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    <h4 
    class="font-sans font-bold text-black text-left">
    Are you sure you want to delete this file: "{{ fileupload.files }}"
    </h4>
    <form method='post'>
        {% csrf_token %}
        <button 
        type='submit' 
        class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 md:px-14 px-10 text-center font-sans font-bold border">
        Delete
        </button>
    </form>
</div>
{% endblock  %}

report/templates/delete_report.html
{% extends "base.html" %}
{% load static tailwind_tags %}

{% block contents %}
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    <h4
    class="font-sans font-bold text-black text-left">
    Are you sure you want to delete this report
    </h4>
    <form method='post'>
        {% csrf_token %}
        <button 
        type='submit'
        class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 md:px-14 px-10 text-center font-sans font-bold border">
        Delete
        </button>
    </form>
</div>
{% endblock  %}

report/templates/file_upload.html
{% extends "base.html" %}
{% load static tailwind_tags %}

{% block contents %}
<div class="my-32 md:mx-80 mx-10 p-5 bg-white rounded-lg">
    <h1 class="text-3xl text-center font-sans font-extrabold">UPLOAD WEEKLY REPORT</h1>
    <br/>
    <br/>
    <form method="post" enctype="multipart/form-data" class="md:w-1/2 mx-auto">
        {% csrf_token %}
        <div class="mb-4">
            <label for="{{ form.user.id_for_label }}" class="block text-lg font-bold text-black">Report by:</label>
            {{ form.user }}
        </div>
        <div class="mb-4">
            <label for="{{ form.files.id_for_label }}" class="block text-lg font-bold text-black">Files:</label>
            {{ form.files }}
        </div>
        <button type="submit" class="bg-blue-900 text-white text-sm md:rounded-2xl rounded-2xl mt-3 py-3 md:px-10 px-10 text-center font-sans font-bold border">
            Upload
        </button>
    </form>
</div>
{% endblock %}

report/templates/list_fileupload.html
{% extends "base.html" %}
{% load static tailwind_tags %}

{% block contents  %}
<div class="my-32 md:mx-80 mx-10 p-5 bg-white rounded-lg">
    {% if fileupload %}
        <h1 class="text-3xl text-center font-sans font-extrabold">UPLOADED WEEKLY REPORT</h1>
        <br />
        {% for file in fileupload %}
        <div class="md:mx-5 md:my-10 md:flex">
            <br/>
            <h4 
            class="font-sans font-bold text-black text-left w-44">
            {{ file.files.name }}
            </h4>
            <br/>
            <div class="mx-2 flex">
                <button class="mx-4">
                    <a 
                    href="{% url 'report:update_fileupload' pk=file.id %}" 
                    class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 md:px-14 px-10 text-center font-sans font-bold border">
                    Update
                    </a>
                </button>
                <button class="mx-4">
                    <a href="{% url 'report:delete_fileupload' pk=file.id %}" 
                    class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 md:px-14 px-10 text-center font-sans font-bold border">
                    Delete
                    </a>
                </button>
            </div>
        </div>
        {% endfor %}
        <br/>
        <br/>
        <div class="">
            <button>
                <a href="{% url 'accounts:logout' %}" 
                class="bg-blue-900 text-white text-sm md:rounded-lg rounded-2xl mt-3 py-3 md:px-14 px-10 text-center font-sans font-bold border">
                Logout
                </a>
            </button>
        </div>
    {% else %}
    <p>No data here</p>
    {% endif %}
</div>
{% endblock  %}

report/templates/list_report.html
{% extends "base.html" %}
{% load static tailwind_tags %}

{% block contents  %}
<div class="my-32 md:mx-80 mx-12 p-5 bg-white rounded-lg">
    {% if report %}
    <div class="mx-5">
        {% for rep in report %}
        <h1 class="text-3xl text-center font-sans font-extrabold">WEEKLY REPORT</h1>
        <br/>
        <li class="font-sans font-bold text-black text-left">
            Report by : {{ rep.user }}</li>
        <li class="font-sans font-bold text-black text-left">
            Supervisor : {{ rep.supervisor }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">TOPICS COVERED FOR EACH DAY OF THE WEEK</h3>
        <li class="font-sans font-bold text-black text-left">
            Monday : {{ rep.monday }}</li>
        <li class="font-sans font-bold text-black text-left">
            Tuesday : {{ rep.tuesday }}</li>
        <li class="font-sans font-bold text-black text-left">
            Wednessday : {{ rep.wednessday }}</li>
        <li class="font-sans font-bold text-black text-left">
            Thursday : {{ rep.thursday }}</li>
        <li class="font-sans font-bold text-black text-left">
            Friday : {{ rep.friday }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">ASSIGNMENT GIVEN FOR EACH DAY OF THE WEEK</h3>
        <li class="font-sans font-bold text-black text-left">
            Monday : {{ rep.monday1 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Tuesday : {{ rep.tuesday1 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Wednessday : {{ rep.wednessday1 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Thursday : {{ rep.thursday1 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Friday : {{ rep.friday1 }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">PROJECTS GIVEN FOR THE WEEK</h3>
        <li class="font-sans font-bold text-black text-left">
            {{ rep.projects }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">NOTE/STUDY MATERIALS GIVEN TO THE STUDENT FOR THE WEEK</h3>
        <li class="font-sans font-bold text-black text-left">
            {{ rep.study_materials }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">SUCCESS RATING FOR THE WEEK</h3>
        <li class="font-sans font-bold text-black text-left">
            {{ rep.rating }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">CHALLENGES FACED ON DUTY</h3>
        <li class="font-sans font-bold text-black text-left">
            {{ rep.challenges }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">DAILY RESUMPTION TIME</h3>
        <li class="font-sans font-bold text-black text-left">
            Monday : {{ rep.monday2 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Tuesday : {{ rep.tuesday2 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Wednessday : {{ rep.wednessday2 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Thursday : {{ rep.thursday2 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Friday : {{ rep.friday2 }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">SOCIAL MEDIA POSTING</h3>
        <li class="font-sans font-bold text-black text-left">
            Whatsapp : {{ rep.whatsapp }}</li>
        <li class="font-sans font-bold text-black text-left">
            Facebook : {{ rep.facebook }}</li>
        <li class="font-sans font-bold text-black text-left">
            Twitter : {{ rep.twitter }}</li>
        <li class="font-sans font-bold text-black text-left">
            Instagram : {{ rep.instagram }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">TOPICS FOR NEXT WEEK</h3>
        <li class="font-sans font-bold text-black text-left">
            Monday : {{ rep.monday3 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Tuesday : {{ rep.tuesday3 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Wednessday : {{ rep.wednessday3 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Thursday : {{ rep.thursday3 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Friday : {{ rep.friday3 }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">SUGGESTIONS TO MANAGEMENT</h3>
        <li class="font-sans font-bold text-black text-left">
            {{ rep.sugestions }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">DURATION REMAINING FOR TRAINING</h3>
        <li class="font-sans font-bold text-black text-left">
            Weeks : {{ rep.total_weeks }}</li>
        <br/>
        <h3 class="text-lg font-sans font-extrabold">PARTICIPATION IN STAFF WHATSAPP GROUP</h3>
        <li class="font-sans font-bold text-black text-left">
            Monday : {{ rep.monday4 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Tuesday : {{ rep.tuesday4 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Wednessday : {{ rep.wednessday4 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Thursday : {{ rep.thursday4 }}</li>
        <li class="font-sans font-bold text-black text-left">
            Friday : {{ rep.friday4 }}</li>
        <br/>
        <div class="md:flex">
            <button class="my-10">
                <a 
                href="{% url 'report:update_report' pk=rep.id %}" 
                class="bg-blue-900 text-white text-sm md:rounded-2xl rounded-2xl mt-3 py-3 md:px-10 px-10 text-center font-sans font-bold border">
                Update
                </a>
            </button>
            <button>
                <a 
                href="{% url 'report:delete_report' pk=rep.id %}" 
                class="bg-blue-900 text-white text-sm md:rounded-2xl rounded-2xl mt-3 py-3 md:px-10 px-10 text-center font-sans font-bold border">
                Delete
                </a>
            </button>
            <button>
                <a 
                href="{% url 'report:pdf_view' %}"
                class="bg-blue-900 text-white text-sm md:rounded-2xl rounded-2xl mt-3 py-3 md:px-10 px-10 text-center font-sans font-bold border">
                Send
                </a>
            </button>
            <button>
                <a 
                href="{% url 'report:pdf_download' %}"
                class="bg-blue-900 text-white text-sm md:rounded-2xl rounded-2xl mt-3 py-3 md:px-10 px-10 text-center font-sans font-bold border">
                Download
                </a>
            </button>
        </div>
        <br/>
        {% endfor %}
    </div>
    {% else %}
    <p>No data here</p>
    {% endif %}
    <br/>
    <div class="">
        <button>
            <a 
            href="{% url 'accounts:logout' %}" 
            class="bg-blue-900 text-white text-sm md:rounded-2xl rounded-2xl mt-3 py-3 md:px-14 px-10 text-center font-sans font-bold border">
            Logout
            </a>
        </button>
    </div>
</div>
{% endblock  %}

report/templates/update_fileupload.html
{% extends "base.html" %}
{% load static tailwind_tags %}

{% block contents %}
<div class="my-32 md:mx-80 mx-10 p-5 bg-white rounded-lg">
    <h1 class="text-3xl text-center font-sans font-extrabold">UPLOAD WEEKLY REPORT</h1>
    <br/>
    <br/>
    <form method="post" enctype="multipart/form-data" class="md:w-1/2 mx-auto">
        {% csrf_token %}
        <div class="mb-4">
            <label for="{{ form.user.id_for_label }}" class="block text-lg font-bold text-black">Report by:</label>
            {{ form.user }}
        </div>
        <div class="mb-4">
            <label for="{{ form.files.id_for_label }}" class="block text-lg font-bold text-black">Files:</label>
            {{ form.files }}
        </div>
        <button type="submit" class="bg-blue-900 text-white text-sm md:rounded-2xl rounded-2xl mt-3 py-3 md:px-10 px-10 text-center font-sans font-bold border">
            Upload
        </button>
    </form>
</div>
{% endblock %}